version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server 
    volumes: 
      - cache:/data
  activemq:
    image: rmohr/activemq:5.10.0
    container_name: activemq
    environment:
      - "TZ=Europe/Amsterdam"
    volumes:
      - "./activemq/activemq.xml:/conf/activemq.xml"
    ports:
      - "61616:61613" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://localhost:8161/admin (admin:admin)
volumes:
  cache:
    driver: local